<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PlaywrightTAF.Core\PlaywrightTAF.Core.csproj" />
    <ProjectReference Include="..\PlaywrightTAF.UI\PlaywrightTAF.UI.csproj" />
    <ProjectReference Include="..\PlaywrightTAF.API\PlaywrightTAF.API.csproj" />
    <ProjectReference Include="..\Performance\Performance.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Allure.NUnit" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.Playwright" />
    <PackageReference Include="Microsoft.Playwright.NUnit" />
    <PackageReference Include="ReportPortal.Shared" />
    <PackageReference Include="ReportPortal.VSTest.TestLogger" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ReportPortal.config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="test.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Authentication\AuthStates\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

</Project>
